### PR TITLE
fix compression

### PR DESCRIPTION
**Pull request by lgrootnoob**
ignore the extra derp commits, they won't hurt anything. if you'd like to just cherry da94a829305f1c217cfdf6771cb1faca0917e3b9 and ignore this one then go ahead.

### CODE REVIEW

**Comment by lgrootnoob** [comment]
or i can redo this pull request in (1/2) (2/2) fashion without the derp. it's up to how lazy you want to be :p

**Comment by xc-racer99** [comment]
Yeah, I don't particularly like the way this is set up.  I don't want to merge a merge, plus I'd prefer to keep the language clean on the commit messages.
Also, the update omni_fascinatemtd_defconfig thing that you're trying to add in is already in the repository, plus you did a typo on your version.  I think I'll manually cherry-pick the earlier commit if I find that its needed.

**Comment by xc-racer99** [comment]
Are you sure this is necessary?  I don't get any of the "arch/arm/boot/compressed/head.S:698: Warning: (null)" when building the kernel, which is what da94a82 attempts to fix

**Comment by lgrootnoob** [comment]
> I think I'll manually cherry-pick the earlier commit if I find that its needed.

Lol, i'd recommend that.
I had to use this otherwise it wouldn't build. Are you using gcc 4.7 on the kernel?

**Comment by xc-racer99** [comment]
Ah, that's where the issue lies.  Yep, I'm using gcc 4.7 with the kernel.  I had instability/unable to boot on the Galaxy S 4G when I used 4.8.

**Comment by lgrootnoob** [comment]
THAT F******\* EXPLAINS EVERYTHING. where is the gun to head emoji :|

**Comment by lgrootnoob** [comment]
holy f**\* this build is smooth though

**Pull request closed without merging**
